#!/usr/bin/env bash
#
# Push Gmail-related secrets to a GitHub repository using a generated env file.
# Assumes `gh` is installed and already authenticated with access to repo secrets.
#
# Usage:
#   ./push-secrets.sh --env-file /path/to/gmail-env.sh [--repo org/repo]
#
# The env file is expected to contain `export NAME=value` lines generated by
# test/gmail/refresh-token.py --output-env.

set -euo pipefail

ENV_FILE=""
REPO=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file)
      ENV_FILE="$2"
      shift 2
      ;;
    --repo)
      REPO="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "$ENV_FILE" ]]; then
  echo "Usage: $0 --env-file /path/to/gmail-env.sh [--repo org/repo]" >&2
  exit 1
fi

if [[ ! -r "$ENV_FILE" ]]; then
  echo "Env file not readable: $ENV_FILE" >&2
  exit 1
fi

if [[ -z "$REPO" ]]; then
  if ! REPO=$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null); then
    echo "Failed to detect repo; pass --repo org/repo" >&2
    exit 1
  fi
fi

echo "Using repo: $REPO"
echo "Reading env exports from: $ENV_FILE"

declare -a VARS=(
  KONGCTL_E2E_GMAIL_REFRESH_TOKEN
  KONGCTL_E2E_GMAIL_ACCESS_TOKEN
  KONGCTL_E2E_GMAIL_CLIENT_ID
  KONGCTL_E2E_GMAIL_CLIENT_SECRET
  KONGCTL_E2E_GMAIL_ADDRESS
)

for var in "${VARS[@]}"; do
  line=$(grep -E "^export ${var}=" "$ENV_FILE" | tail -n1 || true)
  if [[ -z "$line" ]]; then
    echo "Skipping ${var}: not found in env file"
    continue
  fi
  value=${line#export ${var}=}
  if [[ -z "$value" ]]; then
    echo "Skipping ${var}: empty value"
    continue
  fi
  echo "Setting ${var} in ${REPO}"
  gh secret set "$var" --repo "$REPO" --body "$value"
done
