# E-Commerce Team - Products API Configuration  
# Team: ecommerce@example.com
# Owner: E-Commerce Team

ref: products-api
name: !file ./specs/products.yaml#info.title
description: !file ./specs/products.yaml#info.description
version: !file ./specs/products.yaml#info.version
labels:
  team: ecommerce
  owner: ecommerce-team
  business_unit: retail
  criticality: high
kongctl:
  protected: false

versions:
  - ref: products-api-v2
    name: !file ./specs/products.yaml#info.version
    gateway_service:
      control_plane_id: "550e8400-e29b-41d4-a716-446655440000"
      id: "550e8400-e29b-41d4-a716-446655440003"
    spec: !file ./specs/products.yaml

# E-commerce team manages their own implementations
implementations:
  - ref: products-api-prod-impl
    service:
      control_plane_id: "550e8400-e29b-41d4-a716-446655440000"
      id: "550e8400-e29b-41d4-a716-446655440004"

  - ref: products-api-staging-impl
    service:
      control_plane_id: "550e8400-e29b-41d4-a716-446655440001"
      id: "550e8400-e29b-41d4-a716-446655440005"