package common

// View parent type identifiers used by Konnect tableview detail contexts,
// child views, and child loader registration.
const (
	ViewParentAPI                           = "api"
	ViewParentAPIDocument                   = "api-document"
	ViewParentAPIImplementation             = "api-implementation"
	ViewParentAPIPublication                = "api-publication"
	ViewParentAPIVersion                    = "api-version"
	ViewParentAuthStrategy                  = "auth-strategy"
	ViewParentBackendCluster                = "backend-cluster"
	ViewParentCatalogService                = "catalog_service"
	ViewParentConsumePolicy                 = "consume-policy"
	ViewParentConsumerGroup                 = "consumer-group"
	ViewParentControlPlane                  = "control-plane"
	ViewParentDataPlaneCertificate          = "data-plane-certificate"
	ViewParentDCRProvider                   = "dcr-provider"
	ViewParentEventGateway                  = "event-gateway"
	ViewParentGatewayConsumer               = "gateway-consumer"
	ViewParentGatewayPlugin                 = "gateway-plugin"
	ViewParentGatewayRoute                  = "gateway-route"
	ViewParentGatewayService                = "gateway-service"
	ViewParentListener                      = "listener"
	ViewParentListenerPolicy                = "listener-policy"
	ViewParentOrganization                  = "organization"
	ViewParentPortal                        = "portal"
	ViewParentPortalApplication             = "portal-application"
	ViewParentPortalApplicationRegistration = "portal-application-registration"
	ViewParentPortalDeveloper               = "portal-developer"
	ViewParentPortalIdentityProvider        = "portal-identity-provider"
	ViewParentPortalPage                    = "portal-page"
	ViewParentPortalSnippet                 = "portal-snippet"
	ViewParentPortalTeam                    = "portal-team"
	ViewParentPortalTeamRole                = "portal-team-role"
	ViewParentProducePolicy                 = "produce-policy"
	ViewParentSchemaRegistry                = "schema-registry"
	ViewParentStaticKey                     = "static-key"
	ViewParentSystemAccount                 = "system-account"
	ViewParentTeam                          = "team"
	ViewParentTLSTrustBundle                = "tls-trust-bundle"
	ViewParentUpstream                      = "upstream"
	ViewParentUpstreamTarget                = "upstream-target"
	ViewParentVirtualCluster                = "virtual-cluster"
	ViewParentVirtualClusterClusterPolicy   = "cluster-policy"
)

// View field identifiers used by Konnect tableview child loader registration.
const (
	ViewFieldApplications          = "applications"
	ViewFieldAuthSettings          = "auth-settings"
	ViewFieldBackendClusters       = "backend-clusters"
	ViewFieldClusterPolicies       = "cluster-policies"
	ViewFieldConsumePolicies       = "consume-policies"
	ViewFieldConsumers             = "consumers"
	ViewFieldConsumerGroups        = "consumer-groups"
	ViewFieldContent               = "content"
	ViewFieldDataPlaneCertificates = "data-plane-certificates"
	ViewFieldDevelopers            = "developers"
	ViewFieldDocuments             = "documents"
	ViewFieldIdentityProviders     = "identity-providers"
	ViewFieldImplementations       = "implementations"
	ViewFieldListeners             = "listeners"
	ViewFieldPages                 = "pages"
	ViewFieldPlugins               = "plugins"
	ViewFieldPolicies              = "policies"
	ViewFieldProducePolicies       = "produce-policies"
	ViewFieldPublications          = "publications"
	ViewFieldRegistrations         = "registrations"
	ViewFieldRoutes                = "routes"
	ViewFieldSchemaRegistries      = "schema-registries"
	ViewFieldServices              = "services"
	ViewFieldSnippets              = "snippets"
	ViewFieldSpec                  = "spec"
	ViewFieldStaticKeys            = "static-keys"
	ViewFieldSystemAccounts        = "system-accounts"
	ViewFieldTargets               = "targets"
	ViewFieldTeamRoles             = "team-roles"
	ViewFieldTeams                 = "teams"
	ViewFieldTLSTrustBundles       = "tls-trust-bundles"
	ViewFieldUpstreams             = "upstreams"
	ViewFieldVersions              = "versions"
	ViewFieldVirtualClusters       = "virtual-clusters"
)

// View resource selectors used by the Konnect navigator.
const (
	ViewResourceAPIs            = "apis"
	ViewResourceAuthStrategies  = "auth-strategies"
	ViewResourceCatalogServices = "catalog-services"
	ViewResourceControlPlanes   = "control-planes"
	ViewResourceDCRProviders    = "dcr-providers"
	ViewResourceEventGateways   = "event-gateways"
	ViewResourceOrganization    = "organization"
	ViewResourcePortals         = "portals"

	ViewAliasAPIs                      = "apis"
	ViewAliasApplicationAuthStrategies = "application-auth-strategies"
	ViewAliasAuthStrategies            = "auth-strategies"
	ViewAliasCatalog                   = "catalog"
	ViewAliasCatalogServices           = "catalog-services"
	ViewAliasCatalogServicesUnderscore = "catalog_services"
	ViewAliasControlPlanes             = "control-planes"
	ViewAliasEventGateways             = "event-gateways"
	ViewAliasEventGatewayShort         = "egw"
	ViewAliasGatewayControlPlanes      = "gateway control-planes"
	ViewAliasOrganization              = "organization"
	ViewAliasOrganizationShort         = "org"
	ViewAliasPortals                   = "portals"
	ViewAliasDCRProviders              = "dcr-providers"
)
