version: "2"
run:
  build-tags:
    - integration
linters:
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - goconst
    - gomodguard
    - gosec
    - importas
    - lll
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - wastedassign
  settings:
    goconst:
      min-occurrences: 10
    gomodguard:
      blocked:
        modules:
          - github.com/ghodss/yaml:
              recommendations:
                - sigs.k8s.io/yaml
          - gopkg.in/yaml.v2:
              recommendations:
                - sigs.k8s.io/yaml
          - gopkg.in/yaml.v3:
              recommendations:
                - sigs.k8s.io/yaml
          - github.com/pkg/errors:
              recommendations:
                - fmt
                - errors
          - golang.org/x/net/context:
              recommendations:
                - context
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: state/indexers/md5Indexer.*
        text: weak cryptographic primitive
      - linters:
          - gosec
        path: tests/integration/
        text: TLS MinVersion too low
      - linters:
          - gosec
        path: _test\.go
        text: weak random number generator
      - linters:
          - errcheck
        path: _test\.go
        text: Error return value
      - linters:
          - gosec
        path: file/codegen/main.go
        text: Expect WriteFile permissions to be 0600 or less
      - linters:
          - unparam
          - unused
        path: test_.*
      - linters:
          - staticcheck
        text: 'SA1019: rand..*'
      - linters:
          - staticcheck
        text: 'SA1019:.*(Oidc|Saml|PortalClaimMappings|OidcConfig).*is deprecated'
      - linters:
          - revive
        paths: 
          - internal/declarative/errors/
          - internal/cmd/common/ 
          - internal/cmd/root/products/konnect/adopt/common
          - internal/cmd/root/products/konnect/api/
          - internal/cmd/root/products/konnect/common/
          - internal/cmd/root/products/konnect/gateway/common/
          - internal/cmd/root/verbs/api/
          - internal/declarative/common/
          - internal/util/
        text: avoid meaningless package names
      - linters:
          - revive
        text: avoid package names that conflict with Go standard library package names
      - linters:
          - gosec
        text: 'G704: SSRF via taint analysis'
      - linters:
          - gosec
        text: 'G702: Command injection via taint analysis'
      - linters:
          - gosec
        text: 'G703: Path traversal via taint analysis'
      - linters:
          - gosec
        text: 'G706: Log injection via taint analysis'
      - linters:
          - gosec
        text: 'G117: Exported struct field .* matches secret pattern'
      - linters:
          - gosec
        text: 'G115: integer overflow conversion'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
