# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w -X internal/root/version.VERSION={{.Version}} -X internal/root/version.COMMIT={{.Commit}}"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - repository:
      owner: kong
      name: homebrew-kongctl
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      branch: kongctl-go-releaser
      pull_request:
        enabled: true
    commit_author:
      name: Rick Spurgeon 
      email: rspurgeon@users.noreply.github.com
    homepage: "https://github.com/kong/kongctl"
    description: Developer CLI for Kong
    skip_upload: auto
    test: |
        system "#{bin}/kongctl", "version"
