# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats: ['zip']
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: auto
  make_latest: false
homebrew_casks:
  - repository:
      owner: kong
      name: homebrew-kongctl
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      branch: main 
      pull_request:
        enabled: false
    commit_author:
      name: Rick Spurgeon 
      email: rspurgeon@users.noreply.github.com
    homepage: "https://github.com/kong/kongctl"
    description: Developer CLI for Kong
    skip_upload: true
