# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
      - goos: windows
        goarch: arm64
        env:
          - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats: ['zip']
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
homebrew_casks:
  - repository:
      owner: kong
      name: homebrew-kongctl
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      branch: main 
      pull_request:
        enabled: false
    commit_author:
      name: Rick Spurgeon 
      email: rspurgeon@users.noreply.github.com
    homepage: "https://github.com/kong/kongctl"
    description: Developer CLI for Kong
    skip_upload: true
