FROM alpine:3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659 AS binary

ARG TARGETARCH

COPY .docker-release/kongctl-linux-amd64 /tmp/kongctl-linux-amd64
COPY .docker-release/kongctl-linux-arm64 /tmp/kongctl-linux-arm64

RUN case "$TARGETARCH" in \
      amd64) cp /tmp/kongctl-linux-amd64 /kongctl ;; \
      arm64) cp /tmp/kongctl-linux-arm64 /kongctl ;; \
      *) echo "unsupported TARGETARCH: $TARGETARCH" >&2; exit 1 ;; \
    esac && chmod 0755 /kongctl

FROM alpine:3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

RUN addgroup -S kongctl && adduser -S kongctl -G kongctl && apk add --no-cache ca-certificates

COPY --from=binary /kongctl /kongctl

USER kongctl
ENTRYPOINT ["/kongctl"]
