// Code generated by mockery. DO NOT EDIT.

package helpers

import (
	context "context"

	components "github.com/Kong/sdk-konnect-go/models/components"

	mock "github.com/stretchr/testify/mock"

	operations "github.com/Kong/sdk-konnect-go/models/operations"
)

// MockControlPlaneAPI is an autogenerated mock type for the ControlPlaneAPI type
type MockControlPlaneAPI struct {
	mock.Mock
}

type MockControlPlaneAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControlPlaneAPI) EXPECT() *MockControlPlaneAPI_Expecter {
	return &MockControlPlaneAPI_Expecter{mock: &_m.Mock}
}

// CreateControlPlane provides a mock function with given fields: ctx, request, opts
func (_m *MockControlPlaneAPI) CreateControlPlane(ctx context.Context, request components.CreateControlPlaneRequest, opts ...operations.Option) (*operations.CreateControlPlaneResponse, error) {
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, request)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateControlPlane")
	}

	var r0 *operations.CreateControlPlaneResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, components.CreateControlPlaneRequest, ...operations.Option) (*operations.CreateControlPlaneResponse, error)); ok {
		return rf(ctx, request, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, components.CreateControlPlaneRequest, ...operations.Option) *operations.CreateControlPlaneResponse); ok {
		r0 = rf(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.CreateControlPlaneResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, components.CreateControlPlaneRequest, ...operations.Option) error); ok {
		r1 = rf(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockControlPlaneAPI_CreateControlPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateControlPlane'
type MockControlPlaneAPI_CreateControlPlane_Call struct {
	*mock.Call
}

// CreateControlPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - request components.CreateControlPlaneRequest
//   - opts ...operations.Option
func (_e *MockControlPlaneAPI_Expecter) CreateControlPlane(ctx any, request any, opts ...any) *MockControlPlaneAPI_CreateControlPlane_Call {
	return &MockControlPlaneAPI_CreateControlPlane_Call{Call: _e.mock.On("CreateControlPlane",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockControlPlaneAPI_CreateControlPlane_Call) Run(run func(ctx context.Context, request components.CreateControlPlaneRequest, opts ...operations.Option)) *MockControlPlaneAPI_CreateControlPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]operations.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.Option)
			}
		}
		run(args[0].(context.Context), args[1].(components.CreateControlPlaneRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockControlPlaneAPI_CreateControlPlane_Call) Return(_a0 *operations.CreateControlPlaneResponse, _a1 error) *MockControlPlaneAPI_CreateControlPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockControlPlaneAPI_CreateControlPlane_Call) RunAndReturn(run func(context.Context, components.CreateControlPlaneRequest, ...operations.Option) (*operations.CreateControlPlaneResponse, error)) *MockControlPlaneAPI_CreateControlPlane_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteControlPlane provides a mock function with given fields: ctx, id, opts
func (_m *MockControlPlaneAPI) DeleteControlPlane(ctx context.Context, id string, opts ...operations.Option) (*operations.DeleteControlPlaneResponse, error) {
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteControlPlane")
	}

	var r0 *operations.DeleteControlPlaneResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) (*operations.DeleteControlPlaneResponse, error)); ok {
		return rf(ctx, id, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) *operations.DeleteControlPlaneResponse); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.DeleteControlPlaneResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...operations.Option) error); ok {
		r1 = rf(ctx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockControlPlaneAPI_DeleteControlPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteControlPlane'
type MockControlPlaneAPI_DeleteControlPlane_Call struct {
	*mock.Call
}

// DeleteControlPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts ...operations.Option
func (_e *MockControlPlaneAPI_Expecter) DeleteControlPlane(ctx any, id any, opts ...any) *MockControlPlaneAPI_DeleteControlPlane_Call {
	return &MockControlPlaneAPI_DeleteControlPlane_Call{Call: _e.mock.On("DeleteControlPlane",
		append([]any{ctx, id}, opts...)...)}
}

func (_c *MockControlPlaneAPI_DeleteControlPlane_Call) Run(run func(ctx context.Context, id string, opts ...operations.Option)) *MockControlPlaneAPI_DeleteControlPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]operations.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockControlPlaneAPI_DeleteControlPlane_Call) Return(_a0 *operations.DeleteControlPlaneResponse, _a1 error) *MockControlPlaneAPI_DeleteControlPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockControlPlaneAPI_DeleteControlPlane_Call) RunAndReturn(run func(context.Context, string, ...operations.Option) (*operations.DeleteControlPlaneResponse, error)) *MockControlPlaneAPI_DeleteControlPlane_Call {
	_c.Call.Return(run)
	return _c
}

// GetControlPlane provides a mock function with given fields: ctx, id, opts
func (_m *MockControlPlaneAPI) GetControlPlane(ctx context.Context, id string, opts ...operations.Option) (*operations.GetControlPlaneResponse, error) {
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetControlPlane")
	}

	var r0 *operations.GetControlPlaneResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) (*operations.GetControlPlaneResponse, error)); ok {
		return rf(ctx, id, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) *operations.GetControlPlaneResponse); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetControlPlaneResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...operations.Option) error); ok {
		r1 = rf(ctx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockControlPlaneAPI_GetControlPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetControlPlane'
type MockControlPlaneAPI_GetControlPlane_Call struct {
	*mock.Call
}

// GetControlPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts ...operations.Option
func (_e *MockControlPlaneAPI_Expecter) GetControlPlane(ctx any, id any, opts ...any) *MockControlPlaneAPI_GetControlPlane_Call {
	return &MockControlPlaneAPI_GetControlPlane_Call{Call: _e.mock.On("GetControlPlane",
		append([]any{ctx, id}, opts...)...)}
}

func (_c *MockControlPlaneAPI_GetControlPlane_Call) Run(run func(ctx context.Context, id string, opts ...operations.Option)) *MockControlPlaneAPI_GetControlPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]operations.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockControlPlaneAPI_GetControlPlane_Call) Return(_a0 *operations.GetControlPlaneResponse, _a1 error) *MockControlPlaneAPI_GetControlPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockControlPlaneAPI_GetControlPlane_Call) RunAndReturn(run func(context.Context, string, ...operations.Option) (*operations.GetControlPlaneResponse, error)) *MockControlPlaneAPI_GetControlPlane_Call {
	_c.Call.Return(run)
	return _c
}

// ListControlPlanes provides a mock function with given fields: ctx, request, opts
func (_m *MockControlPlaneAPI) ListControlPlanes(ctx context.Context, request operations.ListControlPlanesRequest, opts ...operations.Option) (*operations.ListControlPlanesResponse, error) {
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, request)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListControlPlanes")
	}

	var r0 *operations.ListControlPlanesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, operations.ListControlPlanesRequest, ...operations.Option) (*operations.ListControlPlanesResponse, error)); ok {
		return rf(ctx, request, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, operations.ListControlPlanesRequest, ...operations.Option) *operations.ListControlPlanesResponse); ok {
		r0 = rf(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListControlPlanesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, operations.ListControlPlanesRequest, ...operations.Option) error); ok {
		r1 = rf(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockControlPlaneAPI_ListControlPlanes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListControlPlanes'
type MockControlPlaneAPI_ListControlPlanes_Call struct {
	*mock.Call
}

// ListControlPlanes is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.ListControlPlanesRequest
//   - opts ...operations.Option
func (_e *MockControlPlaneAPI_Expecter) ListControlPlanes(ctx any, request any, opts ...any) *MockControlPlaneAPI_ListControlPlanes_Call {
	return &MockControlPlaneAPI_ListControlPlanes_Call{Call: _e.mock.On("ListControlPlanes",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockControlPlaneAPI_ListControlPlanes_Call) Run(run func(ctx context.Context, request operations.ListControlPlanesRequest, opts ...operations.Option)) *MockControlPlaneAPI_ListControlPlanes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]operations.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.Option)
			}
		}
		run(args[0].(context.Context), args[1].(operations.ListControlPlanesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockControlPlaneAPI_ListControlPlanes_Call) Return(_a0 *operations.ListControlPlanesResponse, _a1 error) *MockControlPlaneAPI_ListControlPlanes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockControlPlaneAPI_ListControlPlanes_Call) RunAndReturn(run func(context.Context, operations.ListControlPlanesRequest, ...operations.Option) (*operations.ListControlPlanesResponse, error)) *MockControlPlaneAPI_ListControlPlanes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateControlPlane provides a mock function with given fields: ctx, id, updateControlPlaneRequest, opts
func (_m *MockControlPlaneAPI) UpdateControlPlane(ctx context.Context, id string, updateControlPlaneRequest components.UpdateControlPlaneRequest, opts ...operations.Option) (*operations.UpdateControlPlaneResponse, error) {
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, id, updateControlPlaneRequest)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateControlPlane")
	}

	var r0 *operations.UpdateControlPlaneResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, components.UpdateControlPlaneRequest, ...operations.Option) (*operations.UpdateControlPlaneResponse, error)); ok {
		return rf(ctx, id, updateControlPlaneRequest, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, components.UpdateControlPlaneRequest, ...operations.Option) *operations.UpdateControlPlaneResponse); ok {
		r0 = rf(ctx, id, updateControlPlaneRequest, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.UpdateControlPlaneResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, components.UpdateControlPlaneRequest, ...operations.Option) error); ok {
		r1 = rf(ctx, id, updateControlPlaneRequest, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockControlPlaneAPI_UpdateControlPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateControlPlane'
type MockControlPlaneAPI_UpdateControlPlane_Call struct {
	*mock.Call
}

// UpdateControlPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - updateControlPlaneRequest components.UpdateControlPlaneRequest
//   - opts ...operations.Option
func (_e *MockControlPlaneAPI_Expecter) UpdateControlPlane(ctx any, id any, updateControlPlaneRequest any, opts ...any) *MockControlPlaneAPI_UpdateControlPlane_Call {
	return &MockControlPlaneAPI_UpdateControlPlane_Call{Call: _e.mock.On("UpdateControlPlane",
		append([]any{ctx, id, updateControlPlaneRequest}, opts...)...)}
}

func (_c *MockControlPlaneAPI_UpdateControlPlane_Call) Run(run func(ctx context.Context, id string, updateControlPlaneRequest components.UpdateControlPlaneRequest, opts ...operations.Option)) *MockControlPlaneAPI_UpdateControlPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]operations.Option, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(operations.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(components.UpdateControlPlaneRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockControlPlaneAPI_UpdateControlPlane_Call) Return(_a0 *operations.UpdateControlPlaneResponse, _a1 error) *MockControlPlaneAPI_UpdateControlPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockControlPlaneAPI_UpdateControlPlane_Call) RunAndReturn(run func(context.Context, string, components.UpdateControlPlaneRequest, ...operations.Option) (*operations.UpdateControlPlaneResponse, error)) *MockControlPlaneAPI_UpdateControlPlane_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockControlPlaneAPI creates a new instance of MockControlPlaneAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControlPlaneAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControlPlaneAPI {
	mock := &MockControlPlaneAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
