# Mixed layout - Base configuration
# Common resources that other configs depend on

# Core authentication strategies
application_auth_strategies:
  - ref: main-oauth
    name: "Main OAuth Provider"
    display_name: "Main OAuth Provider"
    strategy_type: openid_connect
    configs:
      openid_connect:
        issuer: "https://auth.example.com"
        client_id: "portal-client"
        client_secret: "${OAUTH_SECRET}"
        scopes: ["openid", "profile", "email"]

# Main portals
portals:
  - ref: public-portal
    name: "Public API Portal"
    custom_domain: "api.example.com"
    is_public: true
    default_application_auth_strategy_id: main-oauth

# Core control planes
control_planes:
  - ref: primary-cp
    name: "Primary Control Plane"
    cluster_type: "CLUSTER_TYPE_CONTROL_PLANE"
    labels:
      environment: "production"
      role: "primary"
    kongctl:
      protected: true