openapi: 3.0.3
info:
  title: Customer Analytics API
  description: Customer data and analytics services (Legacy v1.1)
  version: 1.1.0
  contact:
    name: Team A
    email: team-a@company.com

servers:
  - url: https://api.company.com/customer-analytics/v1
    description: Production server (v1.1 - Legacy)

security:
  - ApiKeyAuth: []

paths:
  /customers:
    get:
      summary: List customers (v1.1)
      operationId: listCustomers
      tags:
        - Customers
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    email:
                      type: string
                    name:
                      type: string

  /customers/{customerId}/events:
    get:
      summary: Get customer events (v1.1)
      operationId: getCustomerEvents
      tags:
        - Events
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer events
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    event_type:
                      type: string
                    timestamp:
                      type: string
                    properties:
                      type: object

  /events:
    post:
      summary: Track event (v1.1)
      operationId: trackEvent
      tags:
        - Events
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: string
                event_type:
                  type: string
                properties:
                  type: object
      responses:
        '201':
          description: Event tracked

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: bearer