name: Copilot Setup Steps
"on":
  push:
    paths:
    - .github/workflows/copilot-setup-steps.yml
  workflow_dispatch: null
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
    - name: Install gh-aw extension
      uses: github/gh-aw/actions/setup-cli@a86e657586e4ac5f549a790628971ec02f6a4a8f # v0.52.1
      with:
        version: v0.52.1
